site_name: EnviroTyping
site_description: EnviroTyping Project Documentation
repo_url: https://github.com/TACC/EnviroTyping
theme: readthedocs
docs_dir: 'doc_files/docs'
pages:
- Home: index.md
- 'Project Scope': project_scope.md
- 'Premium Manual': manual.md
- Workflow:
    - 'Benchmark Known Truth': 'workflow/benchmark.md'
    - 'Post hoc Analysis': 'workflow/profile_by_group.md'
- Tutorials:
    - 'Launcher Module': 'tutorials/launcher_module.md'
- 'Updating the Docs': updating.md


site_author: 'Dave Hiltbrand'
