site_name: EnviroTyping
site_description: EnviroTyping Project Documentation
theme: readthedocs
pages:
- ['index.md', 'Index']
- ['updating.md', 'Updating the Docs']
- ['tutorials/tutorials.md', 'Tutorials', 'Tutorials']
- ['tutorials/launcherModule.md', 'Tutorials', 'TACC Launcher Module']
