site_name: EnviroTyping
site_description: EnviroTyping Project Documentation
repo_url: https://github.com/TACC/EnviroTyping
theme: readthedocs
docs_dir: './md_files'
pages:
- 'Project Scope': index.md
- Workflow:
    - 'Post hoc Analysis': 'workflow/profile_by_group.md'
- 'Premium Manual': manual.md
- Tutorials:
    - 'Launcher Module': 'tutorials/launcher_module.md'
- 'Updating the Docs': updating.md


site_author: 'Dave Hiltbrand'
