site_name: EnviroTyping
site_description: EnviroTyping Project Documentation

pages:
    - Home: 'index.md'
    - Tutorials: 'tutorials.md'
        - 'Launcher Module': 'tutorials/launcherModule.md'
    - Update: 'updating.md'
